function DICOM_View

h.fig=figure(   'Units','normalized',...
                'Position',[0 0 0.8 0.8],...
                'Color',[0.8 0.8 0.8],...
                'Resize','off',...
                'Name','DICOM view');
set(h.fig,'Visible','off');
                                            
h.Pbt=axes(...
                    'Units','normalized',...
                    'Color',[0 0 0],...
                    'Position',[0.01 0.51 0.36 0.48],...
                    'XTick',[],...
                    'YTick',[]);            
h.Pt=axes(...
                    'Units','normalized',... 
                    'Color',[0 0 0],...
                    'Position',[0.015 0.515 .35 .47],...
                    'XTick',[],...
                    'YTick',[]);           
h.Pbs=axes(...
                    'Units','normalized',...
                    'Color',[0 0 0],...
                    'Position',[0.39 0.51 0.36 0.48],...
                    'XTick',[],...
                    'YTick',[]);
h.Ps=axes(...
                    'Units','normalized',...
                    'Color',[0 0 0],...
                    'Position',[0.395 0.515 .35 .47],...
                    'XTick',[],...
                    'YTick',[]);            
h.Pbc=axes(...
                    'Units','normalized',...
                    'Color',[0 0 0],...
                    'Position',[0.01 0.01 0.36 0.48],...
                    'XTick',[],...
                    'YTick',[]);            
h.Pc=axes(...      
                    'Units','normalized',...
                    'Color',[0 0 0],...
                    'Position',[0.015 0.015 .35 .47],...
                    'XTick',[],...
                    'YTick',[]);            
h.P3D=axes(...
                    'Units','normalized',...
                    'Color',[0 0 0],...
                    'Position',[0.39 0.01 .36 .48],...
                	'XTick',[],...
                    'YTick',[],...
                    'ZTick',[]);              
h.L=uipanel(...
                    'FontUnits','normalized',...
                    'BackgroundColor',[1 1 1],...
                    'FontName','Default',...
                    'FontSize',0.14,...  
                    'ForegroundColor',[0 0 0],...
                    'Position',[.76 .79 0.23 0.2],...
                    'Title',sprintf('Load \n'));                  
h.V=uipanel(...
                    'FontUnits','normalized',...
                    'BackgroundColor',[1 1 1],...
                    'FontName','Default',...
                    'FontSize',0.1,...
                    'ForegroundColor',[0 0 0],...
                    'Position',[.76 .47 0.23 0.31],...
                    'Title',sprintf('View \n'));            
h.T=uipanel(...
                    'FontUnits','normalized',...
                    'BackgroundColor',[1 1 1],...
                    'FontName','Default',...
                    'FontSize',0.112,...
                    'ForegroundColor',[0 0 0],...
                    'Position',[.76 .24 0.23 0.22],...
                    'Title',sprintf('Threshold \n  '));                
h.LG=uipanel(...
                    'FontUnits','normalized',...
                    'BackgroundColor',[1 1 1],...
                    'FontName','Default',...
                    'FontSize',0.127,...
                    'ForegroundColor',[0 0 0],...
                    'Position',[.76 .01 0.23 0.22],...
                    'Title',sprintf('Log \n'));               
h.Llist=uicontrol(...
                    'Style','listbox',...
                    'Parent',h.L,... 
                    'FontUnits','normalized',...
                    'Units','normalized',...
                    'BackgroundColor',[1 1 1],...
                    'FontName','Default',...
                    'FontSize',0.2,...
                    'ForegroundColor',[0 0 0],...
                    'Position',[0.1 0.1 0.65 0.58],...
                    'Enable','off');
h.Vsli_t=uicontrol(...
                    'Style','slider',...
                    'Parent',h.V,...
                    'Units','normalized',...
                    'Position',[0.1 0.85 0.8 0.1],...
                    'BackgroundColor',[1 1 1],...
                    'ForegroundColor',[0 0 0],...
                    'Enable','off');            
h.Vsli_s=uicontrol(...
                    'Style','slider',...
                    'Parent',h.V,...
                    'Units','normalized',...
                    'Position',[0.1 0.61 0.8 0.1],...
                    'BackgroundColor',[1 1 1],...
                    'ForegroundColor',[0 0 0],...
                    'Enable','off');           
h.Vsli_c=uicontrol(...
                    'Style','slider',...
                    'Parent',h.V,...
                    'Units','normalized',...
                    'Position',[0.1 0.35 0.8 0.1],...
                    'BackgroundColor',[1 1 1],...
                    'ForegroundColor',[0 0 0],...
                    'Enable','off');
h.Tsli_u=uicontrol(...
                    'Style','slider',...
                    'Parent',h.T,...
                    'Units','normalized',...
                    'Position',[0.1 0.69 0.8 0.1],...
                    'BackgroundColor',[1 1 1],...
                    'ForegroundColor',[0 0 0],...
                    'Enable','off');                  
h.Tsli_l=uicontrol(...
                    'Style','slider',...
                    'Parent',h.T,...
                    'Units','normalized',...
                    'Position',[0.1 0.41 0.8 0.1],...
                    'BackgroundColor',[1 1 1],...
                    'ForegroundColor',[0 0 0],...
                    'Enable','off');
h.Lpath=uicontrol(...
                    'Style','pushbutton',...
                    'Parent',h.L,...
                    'FontUnits','normalized',...
                    'Units','normalized',...
                    'BackgroundColor',[1 1 1],...
                    'FontName','Default',...
                    'FontSize',0.35,...
                    'ForegroundColor',[0 0 0],...
                    'Position',[0.25 0.78 0.5 0.3],...
                    'String','Select Path');                                                            
h.Lload=uicontrol(...
                    'Style','pushbutton',...
                    'Parent',h.L,...
                    'FontUnits','normalized',...
                    'Units','normalized',...
                    'BackgroundColor',[1 1 1],...
                    'FontName','Default',...
                    'FontSize',0.35,...
                    'ForegroundColor',[0 0 0],...
                    'Position',[0.78 0.25 0.2 0.3],...
                    'String','Load',...
                    'Enable','off');
h.Vinvert=uicontrol(...
                    'Style','pushbutton',...
                    'Parent',h.V,...
                    'FontUnits','normalized',...
                    'Units','normalized',...
                    'BackgroundColor',[1 1 1],...
                    'FontName','Default',...
                    'FontSize',0.35,...
                    'ForegroundColor',[0 0 0],...
                    'Position',[0.27 0.05 0.46 0.24],...
                    'String','Invert 3D Axis',...
                    'Enable','off');               
h.Vtxt_t=uicontrol(...
                    'Style','text',...
                    'Parent',h.V,...
                    'FontUnits','normalized',...
                    'Units','normalized',...
                    'BackgroundColor',[1 1 1],...
                    'FontName','Default',...
                    'FontSize',0.6,...
                    'ForegroundColor',[0 0 0],...
                    'Position',[0.075 0.95 0.7 0.1],...
                    'HorizontalAlignment','left',...
                    'String','Transverse View   Slice:');
h.Vtxt_s=uicontrol(...
                    'Style','text',...
                    'Parent',h.V,...
                    'FontUnits','normalized',...
                    'Units','normalized',...
                    'BackgroundColor',[1 1 1],...
                    'FontName','Default',...
                    'FontSize',0.6,...
                    'ForegroundColor',[0 0 0],...
                    'Position',[0.075 0.71 0.7 0.1],...
                    'HorizontalAlignment','left',...
                    'String','Sagittal View     Slice:');
h.Vtxt_c=uicontrol(...
                    'Style','text',...
                    'Parent',h.V,...
                    'FontUnits','normalized',...
                    'Units','normalized',...
                    'BackgroundColor',[1 1 1],...
                    'FontName','Default',...
                    'FontSize',0.6,...
                    'ForegroundColor',[0 0 0],...
                    'Position',[0.075 0.45 0.7 0.1],...
                    'HorizontalAlignment','left',...
                    'String','Coronal View      Slice:');
h.Vtxt_ts=uicontrol(...
                    'Style','text',...
                    'Parent',h.V,...
                    'FontUnits','normalized',...
                    'Units','normalized',...
                    'BackgroundColor',[1 1 1],...
                    'FontName','Default',...
                    'FontSize',0.6,...
                    'ForegroundColor',[0 0 0],...
                    'Position',[0.775 0.95 0.2 0.1],...
                    'HorizontalAlignment','left',...
                    'String','');               
h.Vtxt_ss=uicontrol(...
                    'Style','text',...
                    'Parent',h.V,...
                    'FontUnits','normalized',...
                    'Units','normalized',...
                    'BackgroundColor',[1 1 1],...
                    'FontName','Default',...
                    'FontSize',0.6,...
                    'ForegroundColor',[0 0 0],...
                    'Position',[0.775 0.71 0.2 0.1],...
                    'HorizontalAlignment','left',...
                    'String',''); 
h.Vtxt_cs=uicontrol(...
                    'Style','text',...
                    'Parent',h.V,...
                    'FontUnits','normalized',...
                    'Units','normalized',...
                    'BackgroundColor',[1 1 1],...
                    'FontName','Default',...
                    'FontSize',0.6,...
                    'ForegroundColor',[0 0 0],...
                    'Position',[0.775 0.45 0.2 0.1],...
                    'HorizontalAlignment','left',...
                    'String','');                        
h.Ttxt_u=uicontrol(...
                    'Style','text',...
                    'Parent',h.T,...
                    'FontUnits','normalized',...
                    'Units','normalized',...
                    'BackgroundColor',[1 1 1],...
                    'FontName','Default',...
                    'FontSize',0.45,...
                    'ForegroundColor',[0 0 0],...
                    'HorizontalAlignment','left',...
                    'Position',[0.05 0.85 0.7 0.2],...
                    'String',sprintf('Upper Threshold \n'));               
h.Ttxt_l=uicontrol(...
                    'Style','text',...
                    'Parent',h.T,...
                    'FontUnits','normalized',...
                    'Units','normalized',...
                    'BackgroundColor',[1 1 1],...
                    'FontName','Default',...
                    'FontSize',0.45,...
                    'ForegroundColor',[0 0 0],...
                    'HorizontalAlignment','left',...
                    'Position',[0.05 0.15 0.7 0.2],...
                    'String',sprintf('Lower Threshold \n')); 
h.LGtxt_1=uicontrol(...
                    'Style','text',...
                    'Parent',h.LG,...
                    'FontUnits','normalized',...
                    'Units','normalized',...
                    'BackgroundColor',[1 1 1],...
                    'FontName','Default',...
                    'FontSize',0.5,...
                    'ForegroundColor',[0 0 0],...
                    'HorizontalAlignment','left',...
                    'Position',[0.008 0.73 0.984 0.18],...
                    'String',sprintf(''));
h.LGtxt_2=uicontrol(...
                    'Style','text',...
                    'Parent',h.LG,...
                    'FontUnits','normalized',...
                    'Units','normalized',...
                    'BackgroundColor',[1 1 1],...
                    'FontName','Default',...
                    'FontSize',0.5,...
                    'ForegroundColor',[0 0 0],...
                    'HorizontalAlignment','left',...
                    'Position',[0.008 0.55 0.984 0.18],...
                    'String',sprintf(''));
h.LGtxt_3=uicontrol(...
                    'Style','text',...
                    'Parent',h.LG,...
                    'FontUnits','normalized',...
                    'Units','normalized',...
                    'BackgroundColor',[1 1 1],...
                    'FontName','Default',...
                    'FontSize',0.5,...
                    'ForegroundColor',[0 0 0],...
                    'HorizontalAlignment','left',...
                    'Position',[0.008 0.37 0.984 0.18],...
                    'String',sprintf(''));
h.LGtxt_4=uicontrol(...
                    'Style','text',...
                    'Parent',h.LG,...
                    'FontUnits','normalized',...
                    'Units','normalized',...
                    'BackgroundColor',[1 1 1],...
                    'FontName','Default',...
                    'FontSize',0.5,...
                    'ForegroundColor',[0 0 0],...
                    'HorizontalAlignment','left',...
                    'Position',[0.008 0.19 0.984 0.18],...
                    'String',sprintf(''));
h.LGtxt_5=uicontrol(...
                    'Style','text',...
                    'Parent',h.LG,...
                    'FontUnits','normalized',...
                    'Units','normalized',...
                    'BackgroundColor',[1 1 1],...
                    'FontName','Default',...
                    'FontSize',0.5,...
                    'ForegroundColor',[0 0 0],...
                    'HorizontalAlignment','left',...
                    'Position',[0.008 0.01 0.984 0.18],...
                    'String',sprintf(''));

movegui(h.fig,'center')                      
str=cell(1,5);
set(h.LGtxt_1,'String',str{5});
set(h.LGtxt_2,'String',str{4});
set(h.LGtxt_3,'String',str{3});
set(h.LGtxt_4,'String',str{2});
set(h.LGtxt_5,'String',str{1});
setappdata(h.fig,'str',str);
setappdata(h.fig,'counter',0);                  

set(h.Lpath,'Callback',{@CB_Lpath,h});
set(h.Lload,'Callback',{@CB_Lload,h});
set(h.Vsli_t,'Callback',{@CB_Vsli_t,h});
set(h.Vsli_s,'Callback',{@CB_Vsli_s,h});
set(h.Vsli_c,'Callback',{@CB_Vsli_c,h});
set(h.Vinvert,'Callback',{@CB_Vinvert,h});
set(h.Tsli_u,'Callback',{@CB_Tsli_u,h});
set(h.Tsli_l,'Callback',{@CB_Tsli_l,h});
set(h.fig,'Visible','on')

function CB_Lpath(~,~,h)
cla(h.Pt); cla(h.Ps); cla(h.Pc); cla(h.P3D);
rotate3d(h.Pt,'off'); rotate3d(h.Pbt,'off');
rotate3d(h.Ps,'off'); rotate3d(h.Pbs,'off');
rotate3d(h.Pc,'off'); rotate3d(h.Pbc,'off');
rotate3d(h.P3D,'off');
set(h.Llist,'String','')
set(h.Vtxt_ts,'String','');
set(h.Vtxt_ss,'String','');
set(h.Vtxt_cs,'String','');
set(h.Lload,'Enable','off')
set(h.Llist,'Enable','off')
set(h.Vsli_t,'Enable','off')
set(h.Vsli_s,'Enable','off')
set(h.Vsli_c,'Enable','off')
set(h.Vinvert,'Enable','off')
set(h.Tsli_u,'Enable','off')
set(h.Tsli_l,'Enable','off')
str=getappdata(h.fig,'str');
folder=uigetdir('*.','Please select a directory');
files=dir([folder, '/']);   
inst=cell(1,size(files,1)); 
ser=cell(1,size(files,1));
str{end+1} = strcat(['>> ' datestr(clock) ' Scanning path...']); str(1)=[];
set(h.LGtxt_1,'String',str{5});
set(h.LGtxt_2,'String',str{4});
set(h.LGtxt_3,'String',str{3});
set(h.LGtxt_4,'String',str{2});
set(h.LGtxt_5,'String',str{1});
drawnow();
for i =1:size(files,1)
    try 
        info=dicominfo([folder , '/', files(i).name]);
        inst{i}=info.SOPInstanceUID;
        ser{i}=info.SeriesInstanceUID;
    catch
    end
end; clear i info;
str{end+1} = strcat(['>> ' datestr(clock) ' Scanning path...Done']); str(1)=[];
set(h.LGtxt_1,'String',str{5});
set(h.LGtxt_2,'String',str{4});
set(h.LGtxt_3,'String',str{3});
set(h.LGtxt_4,'String',str{2});
set(h.LGtxt_5,'String',str{1});
drawnow();
files(cellfun('isempty',ser))=[];
ser(cellfun('isempty',ser))=[];
inst(cellfun('isempty',inst))=[];
switch isempty(ser)
    case 0
        [id, ~, idx] = unique(ser);
        label=cell(1,length(id));
        for i = 1:length(id)
            temp = cell2mat(id(i));
            label{i} = strcat(['Series ' num2str(temp(end-5:end)) ' (' num2str(length(find(idx==i))) ' Images)']);
        end; clear i;
        str{end+1} = strcat(['>> ' datestr(clock) ' '   num2str(length(id)) ' series found']); str(1)=[];
        set(h.LGtxt_1,'String',str{5});
        set(h.LGtxt_2,'String',str{4});
        set(h.LGtxt_3,'String',str{3});
        set(h.LGtxt_4,'String',str{2});
        set(h.LGtxt_5,'String',str{1});
        drawnow();
        setappdata(h.fig,'idx',idx);
        setappdata(h.fig,'folder',folder);
        setappdata(h.fig,'files',files);
        setappdata(h.fig,'inst',inst);
        setappdata(h.fig,'str',str);
        set(h.Lload,'Enable','on')
        set(h.Llist,'Enable','on')
        set(h.Llist,'String',label)
    case 1
        cla(h.Pt); cla(h.Ps); cla(h.Pc); cla(h.P3D);
        set(h.Llist,'String','')
        set(h.Vtxt_ts,'String','');
        set(h.Vtxt_ss,'String','');
        set(h.Vtxt_cs,'String','');
        str{end+1} = strcat(['>> ' datestr(clock) ' No DICOM images found']); str(1)=[];
        set(h.LGtxt_1,'String',str{5});
        set(h.LGtxt_2,'String',str{4});
        set(h.LGtxt_3,'String',str{3});
        set(h.LGtxt_4,'String',str{2});
        set(h.LGtxt_5,'String',str{1});
        drawnow();
        setappdata(h.fig,'str',str);
end
end

function CB_Lload(~,~,h)
idx=getappdata(h.fig,'idx');
folder=getappdata(h.fig,'folder');
files=getappdata(h.fig,'files');
inst=getappdata(h.fig,'inst');
str=getappdata(h.fig,'str');
if length(find(idx==get(h.Llist,'Value'))) > 1  
    cla(h.Pt); cla(h.Ps); cla(h.Pc); cla(h.P3D);
    rotate3d(h.Pt,'off'); rotate3d(h.Pbt,'off'); 
    rotate3d(h.Ps,'off'); rotate3d(h.Pbs,'off');
    rotate3d(h.Pc,'off'); rotate3d(h.Pbc,'off');
    rotate3d(h.P3D,'off');
    set(h.Vtxt_ts,'String','');
    set(h.Vtxt_ss,'String','');
    set(h.Vtxt_cs,'String','');
    set(h.Vsli_t,'Enable','off')
    set(h.Vsli_s,'Enable','off')
    set(h.Vsli_c,'Enable','off')        
    set(h.Vinvert,'Enable','off')
    set(h.Tsli_u,'Enable','off')
    set(h.Tsli_l,'Enable','off')
    idx1=find(idx==get(h.Llist,'Value'),1);
    info=dicominfo([folder , '/',files(idx1).name]);
    scale=[info.PixelSpacing(1) info.PixelSpacing(2) info.SliceThickness]; 
    scale=double(scale);
    ct_size=[info.Rows info.Columns length(find(idx==get(h.Llist,'Value')))]; 
    ct_size=double(ct_size);
    ct=zeros(ct_size(1),ct_size(2),ct_size(3));
    temp=sort(inst(idx==get(h.Llist,'Value')));
    str{end+1} = strcat(['>> ' datestr(clock) ' Loading images...']); str(1)=[];
    set(h.LGtxt_1,'String',str{5});
    set(h.LGtxt_2,'String',str{4});
    set(h.LGtxt_3,'String',str{3});
    set(h.LGtxt_4,'String',str{2});
    set(h.LGtxt_5,'String',str{1});
    drawnow();   
    for i = 1:length(temp)
        ct(:,:,i)=double(dicomread([folder ,  '/', files(strcmp(temp(i),inst)==1).name]));
    end; clear i; 
    str{end+1} = strcat(['>> ' datestr(clock) ' Loading images...Done']); str(1)=[];
    set(h.LGtxt_1,'String',str{5});
    set(h.LGtxt_2,'String',str{4});
    set(h.LGtxt_3,'String',str{3});
    set(h.LGtxt_4,'String',str{2});
    set(h.LGtxt_5,'String',str{1});
    drawnow();   
    ct=uint8(ct*255/max(max(max(ct))));
    set(h.Vsli_t,'Min',1,'Max',ct_size(3),'SliderStep',[1/ct_size(3) 0.1],'Value',1);
    set(h.Vsli_s,'Min',1,'Max',ct_size(2),'SliderStep',[1/ct_size(2) 0.1],'Value',1);
    set(h.Vsli_c,'Min',1,'Max',ct_size(1),'SliderStep',[1/ct_size(1) 0.1],'Value',1);
    set(h.Vtxt_ts,'String',[num2str(1), '/', num2str(ct_size(3))]);
    set(h.Vtxt_ss,'String',[num2str(1), '/', num2str(ct_size(2))]);
    set(h.Vtxt_cs,'String',[num2str(1), '/', num2str(ct_size(1))]);
    slice=[1 1 1];
    Trange=[0 2^8-1];
    set(h.Tsli_l,...
                    'Min',0,...
                    'Max',2^8-1,...
                    'SliderStep',[.01 .1],...
                    'Value', 0);
    set(h.Tsli_u,...
                    'Min',0,...
                    'Max',2^8-1,...
                    'SliderStep',[.01 .1],...
                    'Value', 2^8-1);
    imshow(imadjust(ct(:,:,slice(1))),Trange,'Parent',h.Pt); 
    imshow(imadjust(imresize(permute(ct(:,slice(2),:), [3 1 2]), [int16(ct_size(3)*(scale(3)/scale(2))),ct_size(2)])),Trange,'Parent',h.Ps);   
    imshow(imadjust(imresize(permute(ct(slice(3),:,:), [3 2 1]), [int16(ct_size(3)*(scale(3)/scale(1))),ct_size(1)])),Trange,'Parent',h.Pc);   
    str{end+1} = strcat(['>> ' datestr(clock) ' Loading 3D view...']); str(1)=[];
    set(h.LGtxt_1,'String',str{5});
    set(h.LGtxt_2,'String',str{4});
    set(h.LGtxt_3,'String',str{3});
    set(h.LGtxt_4,'String',str{2});
    set(h.LGtxt_5,'String',str{1});
    drawnow();  
    rez = [ceil(ct_size(1)/100) ceil(ct_size(2)/100) ceil(ct_size(3)/100)]; rez=double(rez);
    %%%%%%%%%%%%%%%----- Modified version of vol3d v2 -----%%%%%%%%%%%%%%%%
    model.cdata = []; model.alpha = []; model.xdata = []; model.ydata = []; 
    model.zdata = []; model.parent = []; model.h = []; model.texture = '3D';
    axes(h.P3D);
    model.parent = gca;
    model.cdata = ct; 
    siz = size(model.cdata);
    model.xdata = [0 siz(2)];
    model.ydata = [0 siz(1)];
    model.zdata = [0 siz(3)];
    opts = {'Parent',model.parent,'cdatamapping',[],'alphadatamapping',[],'facecolor','texturemap','edgealpha',0,'facealpha','texturemap'};
    opts{4} = 'scaled';
    opts{6} = 'scaled'; 
    x = [model.xdata(1), model.xdata(2); model.xdata(1), model.xdata(2)];
    y = [model.ydata(1), model.ydata(1); model.ydata(2), model.ydata(2)];
    z = [model.zdata(1), model.zdata(1); model.zdata(1), model.zdata(1)];
    diff = model.zdata(2)-model.zdata(1);
    delta = rez(3)*diff/size(model.cdata,3);
    for n = 1:rez(3):size(model.cdata,3)
        cslice = squeeze(model.cdata(:,:,n));
        aslice = double(squeeze(model.cdata(:,:,n)));
        surface(x,y,z,cslice,'alphadata',aslice,opts{:});
        z = z + delta;
    end
    x = [model.xdata(1), model.xdata(1); model.xdata(1), model.xdata(1)];
    y = [model.ydata(1), model.ydata(1); model.ydata(2), model.ydata(2)];
    z = [model.zdata(1), model.zdata(2); model.zdata(1), model.zdata(2)];
    diff = model.xdata(2)-model.xdata(1);
    delta = rez(2)*diff/size(model.cdata,2);
    for n = 1:rez(2):size(model.cdata,2)
        cslice = squeeze(model.cdata(:,n,:));
        aslice = double(squeeze(model.cdata(:,n,:)));
        surface(x,y,z,cslice,'alphadata',aslice,opts{:});
        x = x + delta;
    end
    x = [model.xdata(1), model.xdata(1); model.xdata(2), model.xdata(2)];
    y = [model.ydata(1), model.ydata(1); model.ydata(1), model.ydata(1)];
    z = [model.zdata(1), model.zdata(2); model.zdata(1), model.zdata(2)];
    diff = model.ydata(2)-model.ydata(1);
    delta = rez(1)*diff/size(model.cdata,1);
    for n = 1:rez(1):size(model.cdata,1)
        cslice = squeeze(model.cdata(n,:,:));
        aslice = double(squeeze(model.cdata(n,:,:)));
        surface(x,y,z,cslice,'alphadata',aslice,opts{:});
        y = y + delta;
    end
    rotate3d(h.P3D,'off'); hold off;
    axis([model.xdata,model.ydata,model.zdata]);
    %%%%%----- End modified version of vol3d v2 -----%%%%%
    str{end+1} = strcat(['>> ' datestr(clock) ' Loading 3D view...Done']); str(1)=[];
    set(h.LGtxt_1,'String',str{5});
    set(h.LGtxt_2,'String',str{4});
    set(h.LGtxt_3,'String',str{3});
    set(h.LGtxt_4,'String',str{2});
    set(h.LGtxt_5,'String',str{1});
    drawnow();  
    setappdata(h.fig,'ct_size',ct_size);
    setappdata(h.fig,'ct',ct);
    setappdata(h.fig,'scale',scale);
    setappdata(h.fig,'str',str);
    setappdata(h.fig,'slice',slice);
    setappdata(h.fig,'Trange',Trange);
    set(h.Vsli_t,'Enable','on')
    set(h.Vsli_s,'Enable','on')
    set(h.Vsli_c,'Enable','on')
    set(h.Vinvert,'Enable','on')
    set(h.Tsli_u,'Enable','on')
    set(h.Tsli_l,'Enable','on')
else
    str{end+1} = strcat(['>> ' datestr(clock) ' Invalid Series']); str(1)=[];
    set(h.LGtxt_1,'String',str{5});
    set(h.LGtxt_2,'String',str{4});
    set(h.LGtxt_3,'String',str{3});
    set(h.LGtxt_4,'String',str{2});
    set(h.LGtxt_5,'String',str{1});
    drawnow();  
    setappdata(h.fig,'str',str);
end
end

function CB_Vsli_t(hObject,~,h)
ct_size=getappdata(h.fig,'ct_size');
ct=getappdata(h.fig,'ct');
Trange=getappdata(h.fig,'Trange');
slice=getappdata(h.fig,'slice');
slice(1)=get(hObject,'Value');
set(h.Vtxt_ts,'String',[num2str(int16(slice(1))), '/', num2str(ct_size(3))])
imshow(imadjust(ct(:,:,int16(slice(1)))),Trange,'Parent',h.Pt);
setappdata(h.fig,'slice',slice);   
end

function CB_Vsli_s(hObject,~,h)
ct_size=getappdata(h.fig,'ct_size');
ct=getappdata(h.fig,'ct');
scale=getappdata(h.fig,'scale');
Trange=getappdata(h.fig,'Trange');
slice=getappdata(h.fig,'slice');
slice(2)=get(hObject,'Value');
set(h.Vtxt_ss,'String',[num2str(int16(slice(2))), '/', num2str(ct_size(2))])
imshow(imadjust(imresize(permute(ct(:,int16(slice(2)),:),[3 1 2]),[int16(ct_size(3)*(scale(3)/scale(1))),ct_size(2)])),Trange,'Parent',h.Ps);
setappdata(h.fig,'slice',slice);
end

function CB_Vsli_c(hObject,~,h)
ct_size=getappdata(h.fig,'ct_size');
ct=getappdata(h.fig,'ct');
scale=getappdata(h.fig,'scale');
Trange=getappdata(h.fig,'Trange');
slice=getappdata(h.fig,'slice');
slice(3)=get(hObject,'Value');
set(h.Vtxt_cs,'String',[num2str(int16(slice(3))), '/', num2str(ct_size(1))])
imshow(imadjust(imresize(permute(ct(int16(slice(3)),:,:),[3 2 1]),[int16(ct_size(3)*(scale(3)/scale(1))),ct_size(1)])),Trange,'Parent',h.Pc);
setappdata(h.fig,'slice',slice);
end

function CB_Vinvert(~,~,h)
counter=getappdata(h.fig,'counter');
counter=counter+1;
switch rem(counter,2) 
    case 1
        set(h.P3D,'zdir','reverse')
    case 0 
        set(h.P3D,'zdir','normal')        
end
setappdata(h.fig,'counter',counter)
end

function CB_Tsli_u (hObject,~,h)
switch sign(get(hObject,'Value')-get(h.Tsli_l,'Value'))
    case 1
        Trange=[get(h.Tsli_l,'Value') get(hObject,'Value')];
        ct_size=getappdata(h.fig,'ct_size');
        ct=getappdata(h.fig,'ct');
        scale=getappdata(h.fig,'scale');
        slice=getappdata(h.fig,'slice');
        imshow(imadjust(ct(:,:,int16(slice(1)))),Trange,'Parent',h.Pt);
        imshow(imadjust(imresize(permute(ct(:,int16(slice(2)),:),[3 1 2]),[int16(ct_size(3)*(scale(3)/scale(1))),ct_size(2)])),Trange,'Parent',h.Ps);
        imshow(imadjust(imresize(permute(ct(int16(slice(3)),:,:),[3 2 1]),[int16(ct_size(3)*(scale(3)/scale(1))),ct_size(1)])),Trange,'Parent',h.Pc);
        setappdata(h.fig,'Trange',Trange);
    case -1
        str=getappdata(h.fig,'str'); 
        str{end+1} = strcat(['>> ' datestr(clock) ' Invalid Threshold']); str(1)=[];
        set(h.LGtxt_1,'String',str{5});
        set(h.LGtxt_2,'String',str{4});
        set(h.LGtxt_3,'String',str{3});
        set(h.LGtxt_4,'String',str{2});
        set(h.LGtxt_5,'String',str{1});
        drawnow();  
        setappdata(h.fig,'str',str);
end
end

function CB_Tsli_l (hObject,~,h)
switch sign(get(h.Tsli_u,'Value')-get(hObject,'Value'))
    case 1
        Trange=[get(hObject,'Value') get(h.Tsli_u,'Value')];
        ct_size=getappdata(h.fig,'ct_size');
        ct=getappdata(h.fig,'ct');
        scale=getappdata(h.fig,'scale');  
        slice=getappdata(h.fig,'slice');
        imshow(imadjust(ct(:,:,int16(slice(1)))),Trange,'Parent',h.Pt);
        imshow(imadjust(imresize(permute(ct(:,int16(slice(2)),:),[3 1 2]),[int16(ct_size(3)*(scale(3)/scale(1))),ct_size(2)])),Trange,'Parent',h.Ps);
        imshow(imadjust(imresize(permute(ct(int16(slice(3)),:,:),[3 2 1]),[int16(ct_size(3)*(scale(3)/scale(1))),ct_size(1)])),Trange,'Parent',h.Pc);
        setappdata(h.fig,'Trange',Trange);
    case -1
        str=getappdata(h.fig,'str');
        str{end+1} = strcat(['>> ' datestr(clock) ' Invalid Threshold']); str(1)=[];
        set(h.LGtxt_1,'String',str{5});
        set(h.LGtxt_2,'String',str{4});
        set(h.LGtxt_3,'String',str{3});
        set(h.LGtxt_4,'String',str{2});
        set(h.LGtxt_5,'String',str{1});
        drawnow();  
        setappdata(h.fig,'str',str);   
end
end
end